# version: "3"
services:
  database:
    # container_name: "database"
    image: postgres:16.2
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_DB=data
      - POSTGRES_USER=admin_psql
      - POSTGRES_PASSWORD=admin_psql
    ports:
      - "5432:5432"
    networks:
      - dev-network
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - media:/backend/media
      - static:/backend/static
      - .:/backend
    networks:
      - dev-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - dev-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile

    depends_on:
      - backend
      - redis
    volumes:
      - media:/backend/media
      - static:/backend/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/ssl:/etc/nginx/ssl
    restart: always
    networks:
      - dev-network
    ports:
      - "80:80"
      - "443:443"



networks:
  dev-network:
    driver: bridge

volumes:
  media:
  static:
  pg_data:
  