# Generated by Django 5.0.3 on 2024-03-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_connection_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='accepted',
        ),
        migrations.AddField(
            model_name='connection',
            name='post_id',
            field=models.IntegerField(default=1),
        ),
    ]
