# Generated by Django 5.0.3 on 2025-06-25 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тариф',
            },
        ),
        migrations.CreateModel(
            name='TestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('post_pk', models.IntegerField(default=0)),
                ('content', models.TextField(verbose_name='Содержание')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('cost', models.CharField(default=False, max_length=255, verbose_name='Цена')),
                ('geolocation', models.CharField(max_length=255, verbose_name='Геолокация')),
                ('condition', models.CharField(max_length=255, verbose_name='Состояние')),
                ('mortage', models.CharField(max_length=255, verbose_name='Рассрочка')),
                ('delivery', models.CharField(max_length=255, verbose_name='Доставка')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('adress', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес')),
                ('lat', models.CharField(blank=True, default='', max_length=255, verbose_name='Широта')),
                ('lng', models.CharField(blank=True, default='', max_length=255, verbose_name='Долгота')),
                ('isActive', models.BooleanField(default=True, verbose_name='Активно')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('isPayed', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('phone', models.CharField(default='', max_length=255, verbose_name='Телефон')),
                ('phone_whatsapp', models.CharField(blank=True, default='', max_length=255, verbose_name='WhatsApp')),
                ('site', models.CharField(blank=True, default='', max_length=255, verbose_name='Сайт')),
                ('telegram', models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram')),
                ('tiktok', models.CharField(blank=True, default='', max_length=255, verbose_name='TikTok')),
                ('facebook', models.CharField(blank=True, default='', max_length=255, verbose_name='Facebook')),
                ('insta', models.CharField(blank=True, default='', max_length=255, verbose_name='Instagram')),
                ('twogis', models.CharField(blank=True, default='', max_length=255, verbose_name='2GIS')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категории')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='post_images/')),
                ('type', models.CharField(default='image', max_length=6)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.post')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('field_value', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app.post')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='app.post')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
