# Generated by Django 5.0.3 on 2025-08-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_post_categories_category_image_post_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='post',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mortage',
        ),
        migrations.AddField(
            model_name='post',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. поля'),
        ),
    ]
