# Generated by Django 5.0.3 on 2025-09-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_post_condition_remove_post_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='global_category',
            field=models.CharField(max_length=255, null=True, verbose_name='Глобальная категория'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, default='defaults/post.png', null=True, upload_to='post_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/avatar.png', null=True, upload_to='profile_images/'),
        ),
    ]
